data:
  sources:
    ## 1.
    ## WRITE DOWN YOUR SAMPLE NAME AND PATH HERE ##
    ## YOU CAN ADD MULTIPLE SAMPLES ##

    ## EXAMPLE ##
    # Patient1: /raw_data/Nanopore_data/Patient1/

    ## IF YOU WANT TO USE TEST DATA, USE THIS LINE ##
    NA03697_test: test-data/

  sources_multiplex:
    ## 1-1.
    ## IF YOU WANT TO DO BARCODE DEMULTIPLEXING, WRITE DOWN YOUR SAMPLE NAME AND PATH HERE ##
    ## YOU CAN ADD MULTIPLE SAMPLES ##

    ## EXAMPLE ##
    # Patient2: /raw_data/Nanopore_data/Patient2_3/
    # Patient3: /raw_data/Nanopore_data/Patient2_3/
    
analysis:
  ## 2.
  ## WRITE DOWN YOUR SAMPLE NAME AND TARGET GENE NAME HERE ##
  ## YOU CAN ADD MULTIPLE TARGET GENES FOR EACH SAMPLE ##

  ## EXAMPLE ##
  # Patient1-DMPK:
  #   source: 'Patient1'
  #   target: 'DMPK'
  # Patient1-CNBP:
  #   source: 'Patient1'
  #   target: 'CNBP'
  # Patient2-DMPK:
  #   source: 'Patient2'
  #   target: 'DMPK'
  # Patient3-DMPK:
  #   source: 'Patient3'
  #   target: 'DMPK'

  ## IF YOU WANT TO USE TEST DATA, USE THIS LINE ##
  NA03697_test-DMPK:
    source: 'NA03697_test'
    target: 'DMPK'

options:
  first_basecalling:
    model: pre-requisites/dorado_models/dna_r9.4.1_e8_fast@v3.4/
    cuda_devices: cuda:all
  second_basecalling:
    model: pre-requisites/dorado_models/dna_r9.4.1_e8_sup@v3.6/
    cuda_devices: cuda:all
  methylation_calling:
    dorado_original_model: pre-requisites/dorado_models/dna_r9.4.1_e8_sup@v3.3/
    dorado_5mCG_model: pre-requisites/dorado_models/dna_r9.4.1_e8_sup@v3.3_5mCG@v0.1/
    cuda_devices: cuda:all
  demultiplexing:
    # 3. WRITE DOWN YOUR BARCODE KIT NAME AND BARCODE NUMBER HERE
    barcode_kit : EXP-NBD104
    barcode_num :
      ## EXAMPLE ##
      # Patient2: barcode01
      # Patient3: barcode02
  on-target_extraction:
    DMPK:
      region: 'chr19:45765000-45773000'
      chromosome: 'chr19'
    CNBP:
      region: 'chr3:129168000-129178000'
      chromosome: 'chr3'
    NOP56:
      region: 'chr20:2648000-2658000'
      chromosome: 'chr20'

  reference: 'pre-requisites/reference/GRCh38.v44'
  repeat_presets: 'pre-requisites/RepeatHMM/bin/reference_sts/hg38/hg38.predefined.pa'

programs:
  repeathmm: pre-requisites/RepeatHMM/bin/repeatHMM.py
  dorado: pre-requisites/dorado-0.9.1-linux-x64/bin/dorado
  modkit: pre-requisites/dist/modkit
  repeathmm_condaenv: repeathmm
  ont-fast5-api_condaenv: ont-fast5-api
  pod5_condaenv: pod5
  dorado_condaenv: dorado
